### ISSUE TITLE
Can't change avatar

### ISSUE THREAD

**Issue by Sawaba** [v0l/snort#491]
**Describe the bug**
Can't upload an image to change my avatar

**To Reproduce**
1. Log In, go to Profile -> Settings -> Edit Avatar
2. File picker opens
3. Choose photo
4. Nothing happens

**Screenshots**
Lots of CORS policy-related issues
![image](https://user-images.githubusercontent.com/1382808/230245947-14670316-6660-4c68-9083-18ffe79eabcc.png)

**Desktop (please complete the following information):**
Tried this using both vanilla Chrome and Arc Browser on a Macbook
Tried with two different snort.social accounts

**Comment by Sawaba** [comment]
Also, I did check out two closed tickets complaining of avatar upload issues, but it looked like those might have had different causes, and were resolved server-side, so it made sense to file a new bug.

**Comment by v0l** [comment]
This may have been a temporary issue, can you confirm if its still not working?

**Comment by Sawaba** [comment]
Nope same exact errors:
1. Access to fetch from origin blocked by CORS policy
2. POST https://void.cat/upload failed
3. Uncaught (in promise) TypeError: Failed to fetch

**Comment by v0l** [comment]
I tested on Chrome and it works fine? What version of chrome are you using
